# Site settings
title: BibleTech
header-img: img/home-bg.jpg
email: j3frea@gmail.com
copyright_name: James Cuénod
description: "Blog on the intersection between the Bible and Technology. Writing about getting Bible things done using the computer - sometimes to do cool stuff, sometimes to do things that shouldn't be complicated but for some reason are."
baseurl: "/bibletech"
url: "http://jcuenod.github.io"
source_url: "https://github.com/jcuenod/bibletech"
twitter_username: jamescuenod
stackoverflow_userid: 123415
github_username: jcuenod
academia_username: JamesCuénod
email_username: j3frea@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
